=== hledakama/jump/jump-web/src/main/webapp/resources/app_config/globalConfiguration.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/globalConfiguration.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE db SYSTEM "globalConfiguration.dtd">

    <db>
    ...
    </db>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT db (version|static)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT version EMPTY>
<!ATTLIST version
    value CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT static (provider)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT provider (kinds|units)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT kinds (kind)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT kind (types)*>
<!ATTLIST kind
    value CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT types (type)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT type (services)*>
<!ATTLIST type
    value CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT services (service)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT service (categories)*>
<!ATTLIST service
    value CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT categories (category)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT category (items)*>
<!ATTLIST category
    value CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT items (item)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT item (settings)*>
<!ATTLIST item
    value CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT settings EMPTY>
<!ATTLIST settings
    value CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT units (unit)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT unit EMPTY>
<!ATTLIST unit
    value CDATA #IMPLIED
  >

=== hledakama/jump/jump-web/src/main/webapp/resources/app_config/globalConfiguration.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE db SYSTEM "globalConfiguration.dtd">
<db>
 <version value="1.01"/>
 <static>
  <provider>
      <kinds>
          <kind value="domestic">
              <types>
                    <type value="beauty">
                        <services>
                            <service value="men hair cut">
                                  <categories>
                                      <category value="african">
                                          <items>
                                                <item value="ras congo">
                                                      <settings value=""/>
                                                </item>
                                                <item value="afro">
                                                      <settings value=""/>
                                                </item>
                                          </items> 
                                      </category>                                                   
                                  </categories> 
                            </service>                 
                        </services>
                    </type>
                    <type value="entertainment">
                        <services>
                            <service value="weeding ceremonies">
                                  <categories>
                                      <category value="honey moon">
                                          <items>
                                                <item value="Cote d'Ivoire">
                                                      <settings value=""/>
                                                </item>
                                                <item value="Canada">
                                                      <settings value=""/>
                                                </item>
                                                <item value="south America">
                                                      <settings value=""/>
                                                </item>
                                                <item value="Ghana">
                                                      <settings value=""/>
                                                </item>
                                          </items> 
                                      </category>                                                   
                                  </categories> 
                            </service>                 
                        </services>
                    </type>
                    <type value="transportation">
                        <services>
                            <service value="garage">
                                  <categories>
                                      <category value="mechanic">
                                          <items>
                                                <item value="wheel replacement">
                                                      <settings value=""/>
                                                </item>
                                                <item value="air filter change">
                                                      <settings value=""/>
                                                </item>
                                                <item value="light controller">
                                                      <settings value=""/>
                                                </item>
                                                <item value="baby sit">
                                                      <settings value=""/>
                                                </item>
                                                <item value="gear">
                                                      <settings value=""/>
                                                </item>
                                          </items> 
                                      </category>                                                   
                                  </categories> 
                            </service>                 
                        </services>
                    </type>
                    <type value="administration">
                        <services>
                            <service value="finance">
                                  <categories>
                                      <category value="annual taxe declaration">
                                          <items>
                                                <item value="family">
                                                      <settings value=""/>
                                                </item>
                                                <item value="single">
                                                      <settings value=""/>
                                                </item>
                                          </items> 
                                      </category>
                                      <category value="tontine">
                                          <items>
                                                <item value="6 mois">
                                                      <settings value=""/>
                                                </item>
                                                <item value="12 mois">
                                                      <settings value=""/>
                                                </item>
                                          </items> 
                                      </category>                                                   
                                  </categories> 
                            </service>
                            <service value="day care">
                                  <categories>
                                      <category value="home full time">
                                          <items>
                                                <item value="babies">
                                                      <settings value=""/>
                                                </item>
                                                <item value="kids">
                                                      <settings value=""/>
                                                </item>
                                          </items> 
                                      </category>
                                      <category value="home part time">
                                          <items>
                                                <item value="babies">
                                                      <settings value=""/>
                                                </item>
                                                <item value="kids">
                                                      <settings value=""/>
                                                </item>
                                          </items> 
                                      </category>                                                                                        
                                  </categories> 
                            </service>  
                            <service value="trainning">
                                  <categories>
                                      <category value="programmimg">
                                          <items>
                                                <item value="java">
                                                      <settings value=""/>
                                                </item>
                                                <item value="c++">
                                                      <settings value=""/>
                                                </item>
                                          </items> 
                                      </category>
                                      <category value="language">
                                          <items>
                                                <item value="english">
                                                      <settings value=""/>
                                                </item>
                                                <item value="french">
                                                      <settings value=""/>
                                                </item>
                                          </items> 
                                      </category>                                                                                        
                                  </categories> 
                            </service>                                                           
                        </services>
                    </type>
                    <type value="safety">
                        <services>
                            <service value="home remote monitoring">
                                  <categories>
                                      <category value="alarm">
                                          <items>
                                                <item value="out door camera installation">
                                                      <settings value=""/>
                                                </item>
                                                <item value="movement sensor">
                                                      <settings value=""/>
                                                </item>
                                          </items>
